definitions:
  main.Address:
    properties:
      city:
        type: string
      house:
        type: string
      lat:
        type: string
      lon:
        type: string
      street:
        type: string
    type: object
  main.GeocodeRequest:
    properties:
      lat:
        type: string
      lng:
        type: string
    type: object
  main.SearchRequest:
    properties:
      query:
        type: string
    type: object
  main.SearchResponse:
    properties:
      addresses:
        items:
          $ref: '#/definitions/main.Address'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: GeoCode API Server
  title: GeoCode API
  version: "1.0"
paths:
  /api/address/geocode:
    post:
      consumes:
      - application/json
      description: Search place address by geocode
      operationId: geocode-handler
      parameters:
      - description: Latitude and Longitude of place
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.GeocodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: List of searched address
          schema:
            $ref: '#/definitions/main.SearchResponse'
        "400":
          description: Bad Request
          schema:
            type: integer
        "403":
          description: Forbidden
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: Geocode search
      tags:
      - search
  /api/address/search:
    post:
      consumes:
      - application/json
      description: Search place by address
      operationId: search-handler
      parameters:
      - description: Search request query
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: List of searched address
          schema:
            $ref: '#/definitions/main.SearchResponse'
        "400":
          description: bad request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: Address Search
      tags:
      - search
swagger: "2.0"
